export const USER_DETAILS = "USER_DETAILS";
export const LOADING = "LOADING";
export const ATTENDANCE = "ATTENDANCE";
export const ALL_USERS_DETAILS = "ALL_USERS_DETAILS";
export const ALL_USERS_ATTENDANCE_DETAILS = "ALL_USERS_ATTENDANCE_DETAILS";




